import QueryProvider from "@/src/providers/query-provider";
import { AppSocketProvider } from "@/src/providers/app-socket-provider";
import type { Metadata } from "next";
import { Manrope, Meow_Script, Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { toastConfig } from "@/src/config/toast";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin", "vietnamese"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const meowScript = Meow_Script({
  variable: "--font-meow-script",
  subsets: ["latin", "vietnamese"],
  weight: ["400"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Tiết Ú - POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${manrope.variable} ${meowScript.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <AppSocketProvider>
            {children}
          </AppSocketProvider>
        </QueryProvider>
        <Toaster toastOptions={toastConfig} />
      </body>
    </html>
  );
}
